image:
  ftp:
    url: 192.168.3.19
    port: 22
    username: crossyf
    password: 853211

server:
  port: 8099
  servlet:
    context-path: /
spring:
  redis:
    host: localhost
    database: 1
    port: 6379
    password:
    timeout: 5000
    jedis:
      pool:
        max-active: 16
        min-idle: 0
        max-idle: 16
        max-wait: -1

    client-name: testRedis
